### ISSUE TITLE
Broken pipeline for repos with more than 1 package.json

### ISSUE THREAD

**Issue by James-Frowen** [openupm/openupm-pipelines#12]
The recent  PR #9  breaks the pipe line for repos with more than 1 package

Example of the broken run: [Project](https://openupm.com/packages/com.miragenet.mirage/?subPage=pipelines) [Failed run](https://dev.azure.com/openupm/openupm/_build/results?buildId=39267&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=05a7d88e-decf-5c29-7849-5d16879a64a4)

Looking at the pipeline it is because `PACKAGEFOLDER` is set to the output of `findPackage.js`, which is now the "wrong package name in" message
https://github.com/openupm/openupm-pipelines/blob/5f4ec39ac994c03e5d64e3d53c9d4da39c2ac718/azure-pipelines.yml#L92

**Comment by James-Frowen** [comment]
I think to fix this and to keep the "wrong package name " message, then it should only be logged after the `finder.on` loop, only if it finds no matches.

**Comment by favoyang** [comment]
Thank you for bringing this to my attention. Yes, the message should be logged when no matches are found. However, the error message doesn't stop the search. It only gets stopped when finder.stop(); is called or the search ends by itself. I will investigate further and get back to you.

**Comment by favoyang** [comment]
Ahh, I see, the package.json file path is parsed from the output.

**Comment by favoyang** [comment]
@all-contributors please add @James-Frowen for bug

**Comment by favoyang** [comment]
Missing versions for `com.miragenet.mirage` have been built.

**Comment by James-Frowen** [comment]
Great, Thanks for fixing this quickly
