### ISSUE TITLE
Some directories are not published

### ISSUE THREAD

**Issue by nowsprinting** [openupm/openupm-pipelines#14]
Some directories are not published at test-helper.monkey package v0.6.0.
It was published until the previous version.

In the test-helper.monkey package, `Editor*`, `Runtime*`, and `Tests*` are specified in files of package.json.
Tests was published Tests.meta and Tests directory.
But, Editor and Runtime only published meta files.

Package:
https://openupm.com/packages/com.nowsprinting.test-helper.monkey

Build log:
https://dev.azure.com/openupm/openupm/_build/results?view=logs&buildId=40601&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=05a7d88e-decf-5c29-7849-5d16879a64a4

**Comment by favoyang** [comment]
It seems something related to the glob rule changed for the `files` field. Our pipeline update from node 14 to 16 this year, could explain the inconsistent.

I'm not sure where it is documented, but seems `*` only applies to files, and skips directories. For example, using both `Editor` and `Editor*` will make sure both the folder `Editor` and the meta file `Editor.meta` are included.

**Comment by nowsprinting** [comment]
Thanks. I try to change the `files` field.
